# @name checkout_step_1_info
POST {{baseStoreUrl}}/checkout/info
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "contactEmail" : "chayelle@evelt.com",
  "addressToken" : "{{addressToken}}",
  "contactFirstName":"Sarah",
  "contactLastName":"Jones"
}

> {%
    client.global.set("cartToken", response.body.cartToken);
    client.global.set("customerPublicToken", response.body.customerToken);
    client.global.set("shipping_method_id", response.body.shippingMethodsJson[0].id);

%}
###

# @name checkout_step_2_shipping_method
POST {{baseStoreUrl}}/checkout/shippingmethod
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "shippingMethodId" : "{{shipping_method_id}}"
}

> {%
    client.global.set("cartToken", response.body.cartToken);
    client.global.set("customerPublicToken", response.body.customerToken);

%}
###

# @name checkout_step_3_payment_pay_now_new_card
POST {{baseStoreUrl}}/checkout/payment
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "nameOnCard": "Jay Klein",
  "cardNumbers": "4354780010152438",
  "expMonth": "01",
  "expYear": "26",
  "cvv": "732",
  "billingAddress": "10 Eros Drive",
  "billingCity": "Airmont",
  "billingState": "NY",
  "billingZip": "10952",
  "billingCountry": "United States",
  "billingPhone": "000000",
  "orderNotePublic": "this is a public note I wrote and submitted through payment checkout api call",
  "po": "123-245jk"
}

> {%
    client.global.set("cartToken", response.body.cartToken);
    //client.global.set("customerPublicToken", response.body.customerToken);
    client.global.set("orderToken", response.body.orderToken);
    client.global.set("cardToken", response.body.cardToken);

%}
###

# @name checkout_step_3_payment_pay_now_saved_card
POST {{baseStoreUrl}}/checkout/payment
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "cardToken": "cc_FJDJ7aboPYqH",
  "sameAsShipping" : "false",
  "orderNotePublic": "this is a public note I wrote and submitted through payment checkout api call",
  "po": "123-245jk"
}

> {%
    client.global.set("cartToken", response.body.cartToken);
    //client.global.set("customerPublicToken", response.body.customerToken);
    client.global.set("orderToken", response.body.orderToken);
    client.global.set("cardToken", response.body.cardToken);

%}
###

# @name checkout_step_3_payment_pay_later_PO
POST {{baseStoreUrl}}/checkout/po
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "po": "123-P9ojd",
  "billingName": "431 Systems LLC",
  "billingAddress": "10 Eros Drive",
  "billingCity": "Airmont",
  "billingState": "NY",
  "billingZip": "10952",
  "billingCountry": "United States",
  "billingPhone": "000000",
  "orderNotePublic": "order processed through PO pathway"
}

> {%
    client.global.set("cartToken", response.body.cartToken);
    //client.global.set("customerPublicToken", response.body.customerToken);
    client.global.set("orderToken", response.body.orderToken);

%}
###

# @name checkout_apply_coupon
POST {{baseStoreUrl}}/checkout/applycoupon
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "couponCode" : "{{couponToken}}"
}

###

# @name checkout_remove_coupon
POST {{baseStoreUrl}}/checkout/removecoupon
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "couponCode" : "{{couponToken}}"
}

###