# @name get_all_collections
GET {{baseStoreUrl}}/collections
token: {{siteToken}}
Content-Type: application/json

> {%
    client.global.set("collectionToken", response.body[0].collectionToken);
%}

###
# @name get_collection_by_collection_token
GET {{baseStoreUrl}}/collections/{{collectionToken}}
token: {{siteToken}}
Content-Type: application/json

> {%
    client.global.set("collectionToken", response.body.collectionToken);

%}

###