# @name get_cards_by_customer
GET {{baseStoreUrl}}/paymentmanager/cards
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

> {%
    client.global.set("cardToken", response.body[0].cardToken);
%}

###

# @name get_card_by_card_token
GET {{baseStoreUrl}}/paymentmanager/cards/{{cardToken}}
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

> {%
    client.global.set("cardToken", response.body.cardToken);
%}

###

# @name edit_card
PUT {{baseStoreUrl}}/paymentmanager/cards/{{cardToken}}
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "nameOnCard": "Jay Klein",
  "cardNumbers": "4354780010152438",
  "expMonth": "01",
  "expYear": "26",
  "cvv": "732",
  "billingAddress": "10 Eros Drive",
  "billingCity": "Airmont",
  "billingState": "NY",
  "billingZip": "10952",
  "billingCountry": "United States",
  "billingPhone": "000000"
}

> {%
    client.global.set("cardToken", response.body.cardToken);
%}

###
# @name add_new_payment_card
POST {{baseStoreUrl}}/paymentmanager/addcard
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "nameOnCard": "Jay Klein",
  "cardNumbers": "4354780010152438",
  "expMonth": "01",
  "expYear": "26",
  "cvv": "732",
  "billingAddress": "10 Eros Drive",
  "billingCity": "Airmont",
  "billingState": "NY",
  "billingZip": "10952",
  "billingCountry": "United States",
  "billingPhone": "000000"
}

> {%
    client.global.set("cardToken", response.body.cardToken);
%}

###

# @name edit_payment_card
PUT {{baseStoreUrl}}/paymentmanager/{{cardToken}}
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

{
  "nameOnCard": "Jay Klein",
  "cardNumbers": "4354780010152438",
  "expMonth": "01",
  "expYear": "26",
  "cvv": "732",
  "billingAddress": "10 Eros Drive",
  "billingCity": "Airmont",
  "billingState": "NY",
  "billingZip": "10952",
  "billingCountry": "United States",
  "billingPhone": "000000"
}

> {%
    client.global.set("cardToken", response.body.cardToken);
%}

###