#@name get_frequently_purchased_list
GET {{baseStoreUrl}}/frequentlyPurchased
token: {{siteToken}}
Content-Type: application/json
###

#@name get_frequently_purchased_list_force_fresh_data_pull
GET {{baseStoreUrl}}/frequentlyPurchased/forceRefresh
token: {{siteToken}}
Content-Type: application/json
###

#@name get_frequently_purchased_list_by_customer
GET {{baseStoreUrl}}/frequentlyPurchased/forceRefresh
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json
###
