# @name get_orders_by_customer
GET {{baseStoreUrl}}/orders/
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

> {%
    client.global.set("orderToken", response.body[0].orderToken)
    client.global.set("customerPublicToken", response.body[0].customerToken)
    %}

###
# @name get_orders_by_order_token
GET {{baseStoreUrl}}/orders/{{orderToken}}
token: {{siteToken}}
customerToken: {{customerPublicToken}}
Content-Type: application/json

> {%
    client.global.set("orderToken", response.body.orderToken)
    client.global.set("customerPublicToken", response.body.customerToken)
    %}

###