#@name create_customer
POST {{baseStoreUrl}}/customers
token: {{siteToken}}
Content-Type: application/json

{
  "customerEmail": "chayelle{{$randomInt}}{{$randomInt}}{{$randomInt}}@evelt.com",
  "customerFirstName": "Chayelle_{{$randomInt}}{{$randomInt}}{{$randomInt}}",
  "customerLastName": "Altmann_{{$randomInt}}{{$randomInt}}{{$randomInt}}",
  "customerPhone": "5619980301",
  "customerPassword": "test123!"
}

> {%
    client.global.set("customerPublicToken3", response.body.customerToken);
    client.global.set("customerEmail3", response.body.customerEmail);
%}
###

# @name trigger_reset_password_email_to_customer
POST {{baseStoreUrl}}/password/forgot
token: {{siteToken}}
Content-Type: application/json

{
  "customerEmail" : "{{customerEmail3}}",
  "newPassword": "test123!"
}
###
# @name reset_password_with_hash
POST {{baseStoreUrl}}/password/restorepassword
token: {{siteToken}}
Content-Type: application/json

{
  "hash" : "{{customerEmail3}}",
  "newPassword": "test123!"
}
###